### ISSUE TITLE
Next TODO: how to resume

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [3forges/pesto-api#1]
* I am on branch `develop`
* I have implemented more logic like error handling on the `pesto-content-type` Endpoint : 
  * Here I only need to add one more error handling: If the `project_id` mandatory parameter, provided in the payload to create a new `PestoContentType`, does not match any existing `PestoProject` `_id`, in the MongoDB, then an HTTP error is sent back as response, just like other error handlers. 
  * Before adding that error handling logic, I need to add the `PestoProject` Endpoint, otherwise I can't create any project, so I can't create any `PestoContentType`
* So I need to create the `PestoProject` full feature, with its endpoint
* After the `PestoProject` feature is complete, I can then finally add the feature for `PestoContent`, so that i can then 👍 : 

```bash
# --- 
#  + - + NEW VERY IMPORTANT :
#  THE NEXT THING I IMPLEMENT IS : 
#    -> PESTO PROJECT FEATURE : it has no foreign key it is a root object of the model
#    -> PESTO CONTENT FEATURE : it has 2 foreign keys, one [project_id] ("FK" to 'PestoProject' entity), and one [type_id] ("FK" to 'PestoContentType' entity) 
#        +-> FIND 'PestoContent' BY 'PestoProject' 
#        +-> FIND 'PestoContent' BY 'PestoContentType'
# 
# --- 
# Ok now we are going to list all 
# [Pesto Content Types] for a given [Project ID]:
# --- 
# 
export PESTO_PRJ_ID="rubbishprjid3modified"
curl -iv -X GET -H 'Accept: application/json' "http://localhost:3000/pesto-content-type/project/${PESTO_PRJ_ID}" | tail -n 1 | jq . 

```

**Comment by Jean-Baptiste-Lasselle** [comment]
* I have my `PestoProject` Endpoint which works,

# NEXT TODO: OK HERE I NEED TO BE ABLE TO ADD A PESTO CONTENT TYPE INTO A PROJECT BY PROJECT NAME NOT BY PROJECT ID

**Comment by Jean-Baptiste-Lasselle** [comment]
I implemented all, now i only need to add 2 rules : 
* [x] cannot add `PestoContentType` if project_id doesn't match existing project
* [x] cannot add `PestoContent` if `project_id` doesn't match existing project
* [x] cannot add pestocontent if `content_type_id` doesn't match existing `PestoContentType`

**Comment by Jean-Baptiste-Lasselle** [comment]
> * I have my `PestoProject` Endpoint which works,
> 
> # NEXT TODO: OK HERE I NEED TO BE ABLE TO ADD A PESTO CONTENT TYPE INTO A PROJECT BY PROJECT NAME NOT BY PROJECT ID

This one i do not implement it yet, its not interesting, the GET requests anyway always pull mongo db `_id` fields, that will be enough to provide a `@pesto/api-client` package to be able to hit the pesto api easily

**Comment by Jean-Baptiste-Lasselle** [comment]
https://github.com/3forges/poc-frontmatter-schema/issues/1 gives me details about the next and last task: 

### Choose a frontmatter management strategy
